//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007Assignment2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DefaultConnectionEF : DbContext
    {
        public DefaultConnectionEF()
            : base("name=DefaultConnectionEF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BibleBasicEnglish> BibleBasicEnglishes { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<blog_post> blog_post { get; set; }
        public virtual DbSet<blog_references> blog_references { get; set; }
        public virtual DbSet<blog_title> blog_title { get; set; }
        public virtual DbSet<blogUser> blogUsers { get; set; }
    }
}
