//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BibleBasicEnglish
    {
        public int ID { get; set; }
        public string Book { get; set; }
        public Nullable<int> Chapter { get; set; }
        public Nullable<int> Verse { get; set; }
        public string VerseText { get; set; }
        public Nullable<int> bookNum { get; set; }
    }
}
