//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class blog_post
    {
        public int postID { get; set; }
        public Nullable<int> blogID { get; set; }
        public string post { get; set; }
    
        public virtual blog blog { get; set; }
    }
}
